[package]
name = "omp-launcher"
version = "0.0.1"
description = "open.mp launcher"
authors = ["Amyr Ahmady (iAmir)"]
license = ""
repository = "https://github.com/openmultiplayer/launcher"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]
tauri = { version = "1.4", features = ["shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.32.0", features = ["full"] }
byteorder = "1.4.3"
chardet = "0.2.4"
encoding = "0.2.33"
dll-syringe = "0.15.2"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
