name: "Build"
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build-omp-launcher:
    name: Windows build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Install frontend dependencies
        run: yarn install # change this to npm or pnpm depending on which one you use

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate artifact name
        id: vars
        shell: bash
        run: |
          commit=$(git describe --always --tags "refs/remotes/origin/${HEAD_REF}")
          artifact_name="open.mp-launcher-win-${commit}"
          echo "artifact_name=${artifact_name}" >> $GITHUB_OUTPUT

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.vars.outputs.artifact_name }}
          path: src-tauri/target/release/omp-launcher.exe
          if-no-files-found: error
